// Mapping da nome file FBX ai prefissi esatti delle texture
export const textureMap = {
    "wheel_chair.fbx": { prefix: "wheel_chair/Wheel_chair_", base: "BaseColor" },
    "bed.fbx": { prefix: "bed/Bed_", base: "BaseColor" },
    "door_1.fbx": { prefix: "Door_1/Door_1_", base: "BaseColor" },
    "door_2.fbx": { prefix: "Door_1/Door_1_", base: "BaseColor" },
    "Exit_sign.fbx": { prefix: "exit_sign/Exit_sign_", base: "Base_color" },
    "floor_tile_1.fbx": { prefix: "Floors_1/Floors_1_", base: "BaseColor" },
    "floor_tile_2.fbx": { prefix: "Floors_1/Floors_1_", base: "BaseColor" },
    "IV_Bag.fbx": { prefix: "Iv_bag/IV_Bag_IV_pole_bag_", base: "BaseColor" },
    "IV_Bag_holder.fbx": { prefix: "Iv_pole/IV_pole_bag_", base: "Base_color" },
    "Magazine1.fbx": { prefix: "Magazine/Magazine_", base: "Base_color" },
    "tile_wall.fbx": { prefix: "Walls_1/Walls_1_", base: "BaseColor" },
    "tile_wall_half.fbx": { prefix: "Walls_1/Walls_1_", base: "BaseColor" },
    "tile_window.fbx": { prefix: "Walls_1/Walls_1_", base: "BaseColor" },
    "pillar.fbx": { prefix: "Walls_1/Walls_1_", base: "BaseColor" },
    "ceiling_tile.fbx": { prefix: "ceiling_1/Ceiling_1_", base: "BaseColor" },
    "ceiling_light.fbx": { prefix: "Ceiling_light/Ceiling_light_", base: "BaseColor" },
    "table.fbx": { prefix: "Chairs_table_1/Chairs_tables_1_", base: "BaseColor" },
    "chair.fbx": { prefix: "Chairs_table_1/Chairs_tables_1_", base: "BaseColor" },
    "bench.fbx": { prefix: "Chairs_table_1/Chairs_tables_1_", base: "BaseColor" },
    "cabinet_1.fbx": { prefix: "Chairs_table_1/Chairs_tables_1_", base: "BaseColor" },
    "cabinet_2.fbx": { prefix: "Chairs_table_1/Chairs_tables_1_", base: "BaseColor" },
    "cabinet_3.fbx": { prefix: "Chairs_table_1/Chairs_tables_1_", base: "BaseColor" },
    "tile_doorway_1.fbx": { prefix: "Doorway_1/Doorway_1_", base: "BaseColor" },
    "tile_doorway_2.fbx": { prefix: "Doorway_1/Doorway_1_", base: "BaseColor" },
    "tile_corner.fbx": { prefix: "Doorway_1/Doorway_1_", base: "BaseColor" }
};
